

export const GET_ALL_COMMENT_SAGA = 'GET_ALL_COMMENT_SAGA';
export const GET_ALL_COMMENT = 'GET_ALL_COMMENT'


export const ADD_COMMENT_SAGA = 'ADD_COMMENT_SAGA';
export const ADD_COMMENT = 'ADD_COMMENT';

export const UPDATE_COMMENT_SAGA = 'UPDATE_COMMENT_SAGA';
export const DELETE_COMMENT_SAGA = 'DELETE_COMMENT_SAGA';