

export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA';
export const GET_ALL_PROJECT= 'GET_ALL_PROJECT';
export const GET_PROJECT_CATEGORY_SAGA = 'GET_PROJECT_CATEGORY_SAGA';
export const GET_PROJECT_CATEGORY = 'GET_PROJECT_CATEGORY';
export const EDIT_PROJECT = 'EDIT_PROJECT'
export const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA';
export const GET_PROJECT_DETAIL = 'GET_PROJECT_DETAIL';
export const UPDATE_PROJECT_SAGA = 'UPDATE_PROJECT_SAGA';
export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA';
export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA'