

export const GET_ALL_TASK_TYPE_SAGA = 'GET_ALL_TASK_TYPE_SAGA';
export const GET_ALL_TASK_TYPE = 'GET_ALL_TASK_TYPE';
export const UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS';
export const UPDATE_TASK_STATUS_SAGA = 'UPDATE_TASK_STATUS_SAGA';
export const GET_TASK_DETAIL_SAGA = 'GET_TASK_DETAIL_SAGA';
export const GET_TASK_DETAIL = 'GET_TASK_DETAIL';
export const GET_TASK_COMMENT_SAGA = 'GET_TASK_COMMENT_SAGA';
export const GET_TASK_COMMENT = 'GET_TASK_COMMENT';
export const HANDLE_CHANGE_POST_API_SAGA = 'HANDLE_CHANGE_POST_API_SAGA';
export const CHANGE_TASK_MODEL = 'CHANGE_TASK_MODEL';
export const CHANGE_ASSIGNESS = 'CHANGE_ASSIGNESS';
export const REMOVE_ASSIGNESS = 'REMOVE_ASSIGNESS'


export const CREATE_TASK_SAGA = 'CREATE_TASK_SAGA'