export const HISTORY = 'HISTORY'
export const USER_LOGIN_INFO = 'USER_LOGIN_INFO';
export const USER_TOKEN = 'USER_TOKEN'
export const USER_LOGIN_SAGA = 'USER_LOGIN_SAGA';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_SIGN_UP_SAGA = 'USER_SIGN_UP_SAGA';

export const DELETE_USER_SAGA = 'DELETE_USER_SAGA';
export const REMOVE_USER_PROJECT_SAGA = 'REMOVE_USER_PROJECT_SAGA';

export const GET_ALL_USER_SAGA = 'GET_ALL_USER_SAGA';
export const GET_ALL_USER = 'GET_ALL_USER';

export const ASSIGN_USER_PROJECT_SAGA = 'ASSIGN_USER_PROJECT_SAGA';
export const GET_USER_SEARCH_SAGA = 'GET_USER_SEARCH_SAGA';

export const GET_USER_BY_PROJECTID_SAGA = 'GET_USER_BY_PROJECTID_SAGA';
export const GET_USER_BY_PROJECTID = 'GET_USER_BY_PROJECTID';